### ISSUE TITLE
Crashes when breaking mill in creative mode

### ISSUE THREAD

**Issue by Beanius** [a3626a/HungryMechanics#1]
https://gist.github.com/Beanius/a48322d4672ac6a919759c89485b5154

Basically tried to break the mill while in creative mode, I didn't wait for the mill to stop tho, kinda tried to break it while it was rotating?

**Comment by a3626a** [comment]
It looks likes this crash occurs hardly. In other words, it crashes rarely when millstone is broken.
does this happen every time you break the millstone?

**Comment by Beanius** [comment]
I'm gonna test now.

**Comment by a3626a** [comment]
Okay Thank you.
I am going to test my mod with Optifine.
There will be a fixed version soon.

**Comment by a3626a** [comment]
Even if Optifine is installed, I cannot make this crash by breaking millstone. but i uploaded possibly fixed version. Plz check new version for this bug.

I guess axle also has similar bug. Why don't you check breaking axle with Optifine?

**Comment by Beanius** [comment]
Ait tried breaking axle, and millstone while in creative with Optifine installed. Seems fixed, no crashes! superb work B)

**Comment by a3626a** [comment]
Thank you for your report and test
